from __future__ import annotations

import argparse
import copy

from _bootstrap import add_src_to_path

add_src_to_path()

import torch
from torch.utils.data import DataLoader, Subset

from dual_agent.config import TrainingConfig, load_config
from dual_agent.models.dual_agent import DualAgentSystem
from dual_agent.models.forecaster import PVScenarioForecaster
from dual_agent.models.surrogate import OPFSurrogate
from dual_agent.opendss.lindistflow_torch import TorchLinDistFlowEvaluator
from dual_agent.training.dataset import (
    ScenarioDataset,
    make_complete_graph,
    make_train_test_loaders,
    validate_dataset_matches_config,
)
from dual_agent.training.loops import (
    current_learning_rate,
    disable_training_dropout,
    evaluate_forecaster_loss,
    evaluate_joint_loss,
    evaluate_surrogate_loss,
    make_warmup_cosine_scheduler,
    train_joint_epoch,
    train_surrogate_epoch,
)
from dual_agent.training.tracking import init_swanlab_tracker


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="configs/ieee13.yaml")
    parser.add_argument("--data", default=None, help="Dataset generated by scripts/generate_dataset.py.")
    parser.add_argument("--forecaster-checkpoint", default=None)
    parser.add_argument("--surrogate-checkpoint", default="surrogate.pt")
    parser.add_argument("--checkpoint", default="dual_agent.pt")
    parser.add_argument("--test-fraction", type=float, default=0.2)
    parser.add_argument("--phase3-disable-dropout", action=argparse.BooleanOptionalAction, default=None)
    parser.add_argument("--forecaster-first", action=argparse.BooleanOptionalAction, default=None,
                        help="Adapt the surrogate after each forecaster update.")
    parser.add_argument("--validation-fraction", type=float, default=None,
                        help="Fraction of the original training subset used for stage selection.")
    parser.add_argument("--swanlab", action="store_true", help="Track training metrics with SwanLab.")
    parser.add_argument("--swanlab-project", default="dual-agent-opf")
    parser.add_argument("--swanlab-experiment", default="joint")
    args = parser.parse_args()

    config = load_config(args.config)
    disable_dropout = (config.training.phase3_disable_dropout
                       if args.phase3_disable_dropout is None else args.phase3_disable_dropout)
    forecaster_first = (config.training.phase3_forecaster_first
                        if args.forecaster_first is None else args.forecaster_first)
    validation_fraction = (config.training.phase3_validation_fraction
                           if args.validation_fraction is None else args.validation_fraction)
    torch.manual_seed(config.seed)
    data_path = args.data
    if data_path is None:
        parser.error("--data is required")
    dataset = ScenarioDataset(data_path)
    validate_dataset_matches_config(dataset, config)
    train_loader, test_loader = make_train_test_loaders(
        dataset,
        batch_size=config.training.batch_size,
        test_fraction=args.test_fraction,
        seed=config.seed,
    )
    if not 0 < validation_fraction < 1:
        parser.error("--validation-fraction must be between zero and one")
    original_ids = list(train_loader.dataset.indices)
    order = torch.randperm(len(original_ids), generator=torch.Generator().manual_seed(20260922))
    nval = max(1, int(len(original_ids) * validation_fraction))
    validation_loader = DataLoader(Subset(dataset, [original_ids[i] for i in order[:nval]]),
                                 batch_size=config.training.batch_size)
    train_loader = DataLoader(Subset(dataset, [original_ids[i] for i in order[nval:]]),
                              batch_size=config.training.batch_size, shuffle=True)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    nodes = dataset.pv_history.size(2)
    adjacency = make_complete_graph(nodes)

    forecaster = PVScenarioForecaster(
        pv_feature_dim=config.problem.pv_feature_dim,
        hidden_dim=config.model.hidden_dim,
        horizon_steps=config.problem.horizon_steps,
        scenarios=config.problem.scenarios,
        graph_layers=config.model.graph_layers,
        temporal_layers=config.model.temporal_layers,
        dropout=config.model.dropout,
    )
    surrogate = OPFSurrogate(
        pv_nodes=nodes,
        load_nodes=nodes,
        horizon_steps=config.problem.horizon_steps,
        scenarios=config.problem.scenarios,
        load_feature_dim=config.problem.load_feature_dim,
        hidden_dim=config.model.hidden_dim,
        graph_layers=config.model.graph_layers,
        temporal_layers=config.model.temporal_layers,
        dropout=config.model.dropout,
        battery=config.network.batteries,
        interval_hours=config.problem.interval_hours,
    )
    surrogate.load_state_dict(torch.load(args.surrogate_checkpoint, map_location="cpu"))
    if args.forecaster_checkpoint is not None:
        forecaster.load_state_dict(torch.load(args.forecaster_checkpoint, map_location="cpu"))

    system = DualAgentSystem(forecaster, surrogate).to(device)
    if disable_dropout:
        disable_training_dropout(system)
    evaluator = TorchLinDistFlowEvaluator(
        config.network.dss_master,
        config.network.pv_systems,
        config.network.batteries,
        config.lindistflow,
        config.problem.interval_hours,
    ).to(device)
    forecaster_optimizer = torch.optim.AdamW(
        system.forecaster.parameters(), lr=config.training.joint_learning_rate
    )
    surrogate_optimizer = torch.optim.AdamW(
        system.surrogate.parameters(), lr=config.training.joint_surrogate_learning_rate
    )
    initial_forecast_loss = evaluate_forecaster_loss(system.forecaster, train_loader, adjacency, device)
    forecast_loss_cap = initial_forecast_loss * (1.0 + config.training.joint_forecast_loss_tolerance)
    tracker = init_swanlab_tracker(
        enabled=args.swanlab,
        project=args.swanlab_project,
        experiment_name=args.swanlab_experiment,
        config={
            "trainer": "joint",
            "config": config,
            "data": data_path,
            "forecaster_checkpoint": args.forecaster_checkpoint,
            "surrogate_checkpoint": args.surrogate_checkpoint,
            "checkpoint": args.checkpoint,
            "test_fraction": args.test_fraction,
            "validation_fraction_of_train": validation_fraction,
            "phase3_disable_dropout": disable_dropout,
            "forecaster_first": forecaster_first,
            "device": str(device),
            "initial_forecast_loss": initial_forecast_loss,
            "forecast_loss_cap": forecast_loss_cap,
            "phase3_mode": config.training.phase3_mode,
            "phase3_forecaster_epochs": config.training.phase3_forecaster_epochs,
            "phase3_surrogate_epochs": config.training.phase3_surrogate_epochs,
            "phase3_rounds": config.training.phase3_rounds,
            "joint_training_mode": config.training.joint_training_mode,
            "joint_alternating_updates": config.training.joint_alternating_updates,
            "joint_rounds": config.training.joint_rounds,
            "joint_surrogate_epochs_per_round": config.training.joint_surrogate_epochs_per_round,
            "surrogate_consistency_loss_weight": config.training.surrogate_consistency_loss_weight,
        },
    )

    phase3_mode = config.training.phase3_mode
    active_rounds = config.training.phase3_rounds if phase3_mode == "alternating" else 1
    forecaster_epochs_per_round = (
        _split_epochs(config.training.phase3_forecaster_epochs, active_rounds)
        if phase3_mode != "surrogate_only"
        else [0]
    )
    total_surrogate_epochs = _total_joint_surrogate_epochs(config.training)
    forecaster_scheduler = None
    if not config.training.phase3_reset_forecaster_scheduler_per_round:
        forecaster_scheduler = make_warmup_cosine_scheduler(
            forecaster_optimizer,
            max(1, sum(forecaster_epochs_per_round)),
            len(train_loader),
            config.training.warmup_epochs,
            config.training.min_learning_rate_ratio,
        )
    surrogate_scheduler = make_warmup_cosine_scheduler(
        surrogate_optimizer,
        total_surrogate_epochs,
        len(train_loader),
        config.training.warmup_epochs,
        config.training.min_learning_rate_ratio,
    )
    global_epoch = 0
    tracker_step = 0
    early_stopping_enabled = config.training.phase3_early_stopping_patience > 0
    def validation_metrics():
        return evaluate_joint_loss(system, evaluator, validation_loader, adjacency, device,
            forecast_loss_cap, config.training.joint_forecast_constraint_weight,
            config.training.joint_forecast_loss_weight, config.training.operating_cost_loss_weight,
            config.training.voltage_violation_loss_weight, config.training.line_flow_violation_loss_weight,
            config.training.kw_violation_loss_weight, config.training.soc_violation_loss_weight,
            config.training.terminal_soc_loss_weight)

    def snapshot(model, optimizer, scheduler):
        return copy.deepcopy((model.state_dict(), optimizer.state_dict(),
                              None if scheduler is None else scheduler.state_dict()))

    def restore(state, model, optimizer, scheduler):
        model.load_state_dict(state[0])
        optimizer.load_state_dict(state[1])
        if scheduler is not None and state[2] is not None:
            scheduler.load_state_dict(state[2])

    initial_pair_metrics = validation_metrics()
    best_pair_score = initial_pair_metrics["lindistflow_loss"]
    best_pair_cost = initial_pair_metrics["operating_cost"]
    best_pair_state = copy.deepcopy(system.state_dict())
    schedule = []
    for r, nf in enumerate(forecaster_epochs_per_round, start=1):
        ns = _joint_surrogate_epochs_for_round(config.training, r)
        if forecaster_first and phase3_mode == "alternating":
            schedule.extend([(r, nf, 0), (r, 0, ns)])
        else:
            schedule.append((r, nf, ns))
    try:
        for round_index, forecaster_epochs, surrogate_epochs in schedule:
            surrogate_initial_metrics = validation_metrics()
            surrogate_best_operating_cost = surrogate_initial_metrics["lindistflow_loss"]
            surrogate_best_cost = surrogate_initial_metrics["operating_cost"]
            surrogate_bad_epochs = 0
            surrogate_best_state = snapshot(system.surrogate, surrogate_optimizer, surrogate_scheduler)
            surrogate_early_stopped = False
            forecaster_best_operating_cost = float("inf")
            forecaster_bad_epochs = 0
            forecaster_best_state = None
            forecaster_early_stopped = False
            if config.training.phase3_reset_forecaster_scheduler_per_round and forecaster_epochs:
                for parameter_group in forecaster_optimizer.param_groups:
                    parameter_group["lr"] = config.training.joint_learning_rate
                forecaster_scheduler = make_warmup_cosine_scheduler(
                    forecaster_optimizer,
                    forecaster_epochs,
                    len(train_loader),
                    min(config.training.warmup_epochs, forecaster_epochs),
                    config.training.min_learning_rate_ratio,
                )
            reference_surrogate = None
            if (
                surrogate_epochs
                and config.training.surrogate_consistency_loss_weight > 0.0
            ):
                reference_surrogate = copy.deepcopy(system.surrogate).to(device).eval()
                for parameter in reference_surrogate.parameters():
                    parameter.requires_grad_(False)
            if surrogate_epochs:
                print(
                    f"round={round_index:02d}/{active_rounds:02d} "
                    f"stage=surrogate epochs={surrogate_epochs}"
                )
            for surrogate_epoch in range(surrogate_epochs):
                surrogate_train_metrics = train_surrogate_epoch(
                    system.surrogate,
                    evaluator,
                    train_loader,
                    surrogate_optimizer,
                    adjacency,
                    device,
                    system.forecaster,
                    config.training.operating_cost_loss_weight,
                    config.training.voltage_violation_loss_weight,
                    config.training.line_flow_violation_loss_weight,
                    config.training.kw_violation_loss_weight,
                    config.training.soc_violation_loss_weight,
                    config.training.terminal_soc_loss_weight,
                    surrogate_scheduler,
                    config.training.max_grad_norm,
                    reference_surrogate,
                    config.training.surrogate_consistency_loss_weight,
                )
                surrogate_test_metrics = evaluate_surrogate_loss(
                    system.surrogate,
                    evaluator,
                    test_loader,
                    adjacency,
                    device,
                    system.forecaster,
                    config.training.operating_cost_loss_weight,
                    config.training.voltage_violation_loss_weight,
                    config.training.line_flow_violation_loss_weight,
                    config.training.kw_violation_loss_weight,
                    config.training.soc_violation_loss_weight,
                    config.training.terminal_soc_loss_weight,
                    reference_surrogate,
                    config.training.surrogate_consistency_loss_weight,
                )
                tracker_step += 1
                tracker.log(
                    {
                        "round": round_index,
                        "training_phase": 0,
                        **_surrogate_stage_log_metrics(
                            surrogate_train_metrics,
                            surrogate_test_metrics,
                            current_learning_rate(surrogate_optimizer),
                        ),
                    },
                    step=tracker_step,
                )
                print(
                    f"round={round_index:02d} stage=surrogate "
                    f"epoch={surrogate_epoch + 1:03d} "
                    f"train_loss={surrogate_train_metrics['loss']:.6f} "
                    f"test_loss={surrogate_test_metrics['loss']:.6f}"
                )
                if early_stopping_enabled:
                    validation = validation_metrics()
                    validation_cost = validation["lindistflow_loss"]
                    if (
                        validation_cost
                        < surrogate_best_operating_cost
                        * (1.0 - config.training.phase3_early_stopping_min_delta)
                        and validation["operating_cost"] < surrogate_best_cost
                    ):
                        surrogate_best_operating_cost = validation_cost
                        surrogate_best_cost = validation["operating_cost"]
                        surrogate_best_state = snapshot(system.surrogate, surrogate_optimizer, surrogate_scheduler)
                        surrogate_bad_epochs = 0
                    else:
                        surrogate_bad_epochs += 1
                    if surrogate_bad_epochs >= config.training.phase3_early_stopping_patience:
                        surrogate_early_stopped = True
                        if surrogate_best_state is not None:
                            restore(surrogate_best_state, system.surrogate, surrogate_optimizer, surrogate_scheduler)
                        print(
                            f"round={round_index:02d} stage=surrogate early_stop "
                            f"best_validation_objective={surrogate_best_operating_cost:.6f}"
                        )
                        break

            if early_stopping_enabled:
                restore(surrogate_best_state, system.surrogate, surrogate_optimizer, surrogate_scheduler)
            if reference_surrogate is not None:
                del reference_surrogate

            if forecaster_epochs == 0:
                pair_metrics = validation_metrics()
                if (pair_metrics["lindistflow_loss"] < best_pair_score
                        and pair_metrics["operating_cost"] < best_pair_cost):
                    best_pair_score = pair_metrics["lindistflow_loss"]
                    best_pair_cost = pair_metrics["operating_cost"]
                    best_pair_state = copy.deepcopy(system.state_dict())
                continue
            forecaster_initial_metrics = validation_metrics()
            forecaster_best_operating_cost = forecaster_initial_metrics["lindistflow_loss"]
            forecaster_best_cost = forecaster_initial_metrics["operating_cost"]
            forecaster_best_state = snapshot(system.forecaster, forecaster_optimizer, forecaster_scheduler)
            print(
                f"round={round_index:02d}/{active_rounds:02d} "
                f"stage=forecaster epochs={forecaster_epochs}"
            )
            for round_epoch in range(forecaster_epochs):
                global_epoch += 1
                train_metrics = train_joint_epoch(
                    system,
                    evaluator,
                    train_loader,
                    forecaster_optimizer,
                    adjacency,
                    device,
                    forecast_loss_cap,
                    config.training.joint_forecast_constraint_weight,
                    config.training.joint_forecast_loss_weight,
                    config.training.operating_cost_loss_weight,
                    config.training.voltage_violation_loss_weight,
                    config.training.line_flow_violation_loss_weight,
                    config.training.kw_violation_loss_weight,
                    config.training.soc_violation_loss_weight,
                    config.training.terminal_soc_loss_weight,
                    forecaster_scheduler,
                    config.training.max_grad_norm,
                )
                train_loss = train_metrics["loss"]
                test_metrics = evaluate_joint_loss(
                    system,
                    evaluator,
                    test_loader,
                    adjacency,
                    device,
                    forecast_loss_cap,
                    config.training.joint_forecast_constraint_weight,
                    config.training.joint_forecast_loss_weight,
                    config.training.operating_cost_loss_weight,
                    config.training.voltage_violation_loss_weight,
                    config.training.line_flow_violation_loss_weight,
                    config.training.kw_violation_loss_weight,
                    config.training.soc_violation_loss_weight,
                    config.training.terminal_soc_loss_weight,
                )
                test_loss = test_metrics["loss"]
                metrics = {
                    "round": round_index,
                    "training_phase": 1,
                    "train/loss": train_loss,
                    "test/loss": test_loss,
                    "train/forecast_loss": train_metrics["forecast_loss"],
                    "train/forecast_loss_cap": train_metrics["forecast_loss_cap"],
                    "train/forecast_constraint_violation": train_metrics[
                        "forecast_constraint_violation"
                    ],
                    "train/lindistflow_loss": train_metrics["lindistflow_loss"],
                    "train/lindistflow_operating_cost": train_metrics["operating_cost"],
                    "train/lindistflow_curtailment_cost": train_metrics["curtailment_cost"],
                    "train/battery_dispatch_abs_mean": train_metrics["dispatch_abs_mean"],
                    "train/battery_dispatch_abs_max": train_metrics["dispatch_abs_max"],
                    "train/battery_charge_energy_kwh": train_metrics["charge_energy_kwh"],
                    "train/battery_discharge_energy_kwh": train_metrics[
                        "discharge_energy_kwh"
                    ],
                    "train/battery_soc_min": train_metrics["soc_min"],
                    "train/battery_soc_max": train_metrics["soc_max"],
                    "train/lindistflow_voltage_violation": train_metrics["voltage_violation"],
                    "train/lindistflow_line_flow_violation": train_metrics[
                        "line_flow_violation"
                    ],
                    "train/lindistflow_network_violation": train_metrics["network_violation"],
                    "train/lindistflow_kw_violation": train_metrics["kw_violation"],
                    "train/lindistflow_soc_violation": train_metrics["soc_violation"],
                    "train/lindistflow_terminal_soc_deviation": train_metrics[
                        "terminal_soc_deviation"
                    ],
                    "test/forecast_loss": test_metrics["forecast_loss"],
                    "test/forecast_loss_cap": test_metrics["forecast_loss_cap"],
                    "test/forecast_constraint_violation": test_metrics[
                        "forecast_constraint_violation"
                    ],
                    "test/lindistflow_loss": test_metrics["lindistflow_loss"],
                    "test/lindistflow_operating_cost": test_metrics["operating_cost"],
                    "test/lindistflow_curtailment_cost": test_metrics["curtailment_cost"],
                    "test/battery_dispatch_abs_mean": test_metrics["dispatch_abs_mean"],
                    "test/battery_dispatch_abs_max": test_metrics["dispatch_abs_max"],
                    "test/battery_charge_energy_kwh": test_metrics["charge_energy_kwh"],
                    "test/battery_discharge_energy_kwh": test_metrics["discharge_energy_kwh"],
                    "test/battery_soc_min": test_metrics["soc_min"],
                    "test/battery_soc_max": test_metrics["soc_max"],
                    "test/lindistflow_voltage_violation": test_metrics["voltage_violation"],
                    "test/lindistflow_line_flow_violation": test_metrics[
                        "line_flow_violation"
                    ],
                    "test/lindistflow_network_violation": test_metrics["network_violation"],
                    "test/lindistflow_kw_violation": test_metrics["kw_violation"],
                    "test/lindistflow_soc_violation": test_metrics["soc_violation"],
                    "test/lindistflow_terminal_soc_deviation": test_metrics[
                        "terminal_soc_deviation"
                    ],
                    "learning_rate": current_learning_rate(forecaster_optimizer),
                }
                tracker_step += 1
                tracker.log(metrics, step=tracker_step)
                print(
                    f"round={round_index:02d} stage=forecaster "
                    f"epoch={global_epoch:03d} train_loss={train_loss:.6f} "
                    f"test_loss={test_loss:.6f} "
                    f"forecast_loss={test_metrics['forecast_loss']:.6f} "
                    f"forecast_violation={test_metrics['forecast_constraint_violation']:.6f} "
                    f"lindistflow_loss={test_metrics['lindistflow_loss']:.6f} "
                    f"operating_cost={test_metrics['operating_cost']:.6f} "
                    f"curtailment_cost={test_metrics['curtailment_cost']:.6f} "
                    f"dispatch_abs_mean={test_metrics['dispatch_abs_mean']:.6f} "
                    f"soc_min={test_metrics['soc_min']:.6f} "
                    f"soc_max={test_metrics['soc_max']:.6f} "
                    f"voltage_violation={test_metrics['voltage_violation']:.6f} "
                    f"line_flow_violation={test_metrics['line_flow_violation']:.6f} "
                    f"kw_violation={test_metrics['kw_violation']:.6f} "
                    f"soc_violation={test_metrics['soc_violation']:.6f} "
                    f"terminal_soc_deviation={test_metrics['terminal_soc_deviation']:.6f}"
                )
                if early_stopping_enabled:
                    validation = validation_metrics()
                    validation_cost = validation["lindistflow_loss"]
                    if (
                        validation_cost
                        < forecaster_best_operating_cost
                        * (1.0 - config.training.phase3_early_stopping_min_delta)
                        and validation["operating_cost"] < forecaster_best_cost
                    ):
                        forecaster_best_operating_cost = validation_cost
                        forecaster_best_cost = validation["operating_cost"]
                        forecaster_best_state = snapshot(system.forecaster, forecaster_optimizer, forecaster_scheduler)
                        forecaster_bad_epochs = 0
                    else:
                        forecaster_bad_epochs += 1
                    if forecaster_bad_epochs >= config.training.phase3_early_stopping_patience:
                        forecaster_early_stopped = True
                        if forecaster_best_state is not None:
                            restore(forecaster_best_state, system.forecaster, forecaster_optimizer, forecaster_scheduler)
                        print(
                            f"round={round_index:02d} stage=forecaster early_stop "
                            f"best_validation_objective={forecaster_best_operating_cost:.6f}"
                        )
                        break
            if early_stopping_enabled:
                restore(forecaster_best_state, system.forecaster, forecaster_optimizer, forecaster_scheduler)
            pair_metrics = validation_metrics()
            if (pair_metrics["lindistflow_loss"] < best_pair_score
                    and pair_metrics["operating_cost"] < best_pair_cost):
                best_pair_score = pair_metrics["lindistflow_loss"]
                best_pair_cost = pair_metrics["operating_cost"]
                best_pair_state = copy.deepcopy(system.state_dict())
    finally:
        tracker.finish()

    if early_stopping_enabled:
        system.load_state_dict(best_pair_state)
    torch.save(system.state_dict(), args.checkpoint)


def _split_epochs(total_epochs: int, rounds: int) -> list[int]:
    """Split a fixed epoch budget across rounds without dropping the remainder."""
    base, remainder = divmod(total_epochs, rounds)
    return [base + (index < remainder) for index in range(rounds)]


def _total_joint_surrogate_epochs(training: TrainingConfig) -> int:
    if training.phase3_mode in {"surrogate_only", "alternating"}:
        return max(1, training.phase3_surrogate_epochs)
    return 1


def _joint_surrogate_epochs_for_round(training: TrainingConfig, round_index: int) -> int:
    if training.phase3_mode == "surrogate_only" and round_index == 1:
        return training.phase3_surrogate_epochs
    if training.phase3_mode == "alternating":
        return _split_epochs(training.phase3_surrogate_epochs, training.phase3_rounds)[round_index - 1]
    return 0


def _surrogate_stage_log_metrics(
    train_metrics: dict[str, float],
    test_metrics: dict[str, float],
    learning_rate: float,
) -> dict[str, float]:
    """Map surrogate-stage results onto the joint train/test metric namespace."""
    metric_names = {
        "loss": "loss",
        "operating_cost": "lindistflow_operating_cost",
        "curtailment_cost": "lindistflow_curtailment_cost",
        "dispatch_abs_mean": "battery_dispatch_abs_mean",
        "dispatch_abs_max": "battery_dispatch_abs_max",
        "charge_energy_kwh": "battery_charge_energy_kwh",
        "discharge_energy_kwh": "battery_discharge_energy_kwh",
        "soc_min": "battery_soc_min",
        "soc_max": "battery_soc_max",
        "voltage_violation": "lindistflow_voltage_violation",
        "line_flow_violation": "lindistflow_line_flow_violation",
        "network_violation": "lindistflow_network_violation",
        "kw_violation": "lindistflow_kw_violation",
        "soc_violation": "lindistflow_soc_violation",
        "terminal_soc_deviation": "lindistflow_terminal_soc_deviation",
    }
    logged = {"learning_rate": learning_rate}
    for source, destination in metric_names.items():
        logged[f"train/{destination}"] = train_metrics[source]
        logged[f"test/{destination}"] = test_metrics[source]
    if "surrogate_consistency_loss" in train_metrics:
        logged["train/surrogate_consistency_loss"] = train_metrics["surrogate_consistency_loss"]
        logged["test/surrogate_consistency_loss"] = test_metrics["surrogate_consistency_loss"]
    logged["train/lindistflow_loss"] = train_metrics["loss"]
    logged["test/lindistflow_loss"] = test_metrics["loss"]
    return logged


if __name__ == "__main__":
    main()
