from __future__ import annotations

import argparse

from _bootstrap import add_src_to_path

add_src_to_path()

import torch
from torch.utils.data import DataLoader

from dual_agent.config import load_config
from dual_agent.models.dual_agent import DualAgentSystem
from dual_agent.models.forecaster import PVScenarioForecaster
from dual_agent.models.surrogate import OPFSurrogate
from dual_agent.training.dataset import TeacherDataset, make_complete_graph
from dual_agent.training.loops import train_joint_epoch


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="configs/ieee13.yaml")
    parser.add_argument("--data", default=None, help="Dataset generated by scripts/generate_dataset.py.")
    parser.add_argument(
        "--teacher-data",
        default=None,
        help="Deprecated alias for --data.",
    )
    parser.add_argument("--forecaster-checkpoint", default=None)
    parser.add_argument("--surrogate-checkpoint", default="surrogate.pt")
    parser.add_argument("--checkpoint", default="dual_agent.pt")
    args = parser.parse_args()

    config = load_config(args.config)
    data_path = args.data or args.teacher_data
    if data_path is None:
        parser.error("one of --data or --teacher-data is required")
    dataset = TeacherDataset(data_path)
    loader = DataLoader(dataset, batch_size=config.training.batch_size, shuffle=True)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    nodes = dataset.pv_scenarios.size(-1)
    adjacency = make_complete_graph(nodes)

    forecaster = PVScenarioForecaster(
        pv_feature_dim=config.problem.pv_feature_dim,
        hidden_dim=config.model.hidden_dim,
        horizon_steps=config.problem.horizon_steps,
        scenarios=config.problem.scenarios,
        graph_layers=config.model.graph_layers,
        temporal_layers=config.model.temporal_layers,
        dropout=config.model.dropout,
    )
    surrogate = OPFSurrogate(
        pv_nodes=nodes,
        load_nodes=nodes,
        horizon_steps=config.problem.horizon_steps,
        scenarios=config.problem.scenarios,
        load_feature_dim=config.problem.load_feature_dim,
        hidden_dim=config.model.hidden_dim,
        graph_layers=config.model.graph_layers,
        temporal_layers=config.model.temporal_layers,
        dropout=config.model.dropout,
    )
    surrogate.load_state_dict(torch.load(args.surrogate_checkpoint, map_location="cpu"))
    if args.forecaster_checkpoint is not None:
        forecaster.load_state_dict(torch.load(args.forecaster_checkpoint, map_location="cpu"))

    system = DualAgentSystem(forecaster, surrogate).to(device)
    optimizer = torch.optim.AdamW(system.forecaster.parameters(), lr=config.training.learning_rate)

    for epoch in range(config.training.epochs):
        loss = train_joint_epoch(
            system,
            loader,
            optimizer,
            adjacency,
            device,
            config.training.forecast_loss_weight,
            config.training.decision_loss_weight,
            config.training.risk_loss_weight,
        )
        print(f"epoch={epoch + 1:03d} joint_loss={loss:.6f}")

    torch.save(system.state_dict(), args.checkpoint)


if __name__ == "__main__":
    main()
